name: Build & Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: kethnjtransitalerts-g3ddh7gmbzf3dxd3.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: kethnjtransitalerts-g3ddh7gmbzf3dxd3.azurecr.io/nj-transit-backend:latest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name train-alerts-api \
            --resource-group train-alerts-rg \
            --image kethnjtransitalerts-g3ddh7gmbzf3dxd3.azurecr.io/nj-transit-backend:latest
